#!/bin/sh
set -e

if [ "$OS" = "Windows_NT" ]; then
	target="x86_64-pc-windows-msvc"
	exten=".exe"
else
	case $(uname -sm) in
	"Darwin x86_64") target="x86_64-apple-darwin";;
	*) target="x86_64-unknown-linux-gnu";;
	esac
	exten=""
fi

cargo build --locked --target $target --release

if [ ! -d "./bin" ]; then
	mkdir -p "./bin"
fi

if [ -f "./bin/blazex$exten" ]; then
    rm -r "./bin/blazex$exten"
fi

cp "./target/$target/release/blazex$exten" "./bin/blazex$exten"
strip "./bin/blazex$exten"