#!/bin/sh
set -e

llvm_path="$1"

if [ "$OS" = "Windows_NT" ]; then
	target="x86_64-pc-windows-msvc"
	exe="blazex.exe"
	exten=".exe"
	executable="target/$target/release/$exe"
else
	case $(uname -sm) in
	"Darwin x86_64") target="x86_64-apple-darwin" ;;
	"Darwin arm64") target="aarch64-apple-darwin" ;;
	*) target="x86_64-unknown-linux-gnu" ;;
	esac
	exe="blazex"
	exten=""
	executable="target/$target/release/$exe"
fi

rustup toolchain install nightly
sleep 1
rustup override set nightly
sleep 1
rustup component add rust-src
sleep 1
LLVM_SYS_110_PREFIX="$llvm_path" cargo +nightly build --locked --target $target --release
strip $executable

if [ ! -d "bin" ]; then
	mkdir -p "bin"
fi
if [ -f "bin/$exe" ]; then
    rm -r "bin/$exe"
fi

cp $executable "bin/$target$exten"
