[package]
name = "blazescript"
version = "0.0.1"
authors = ["RoMeAh <romeah@blazify.rocks>"]
edition = "2018"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/BlazifyOrg/blazescript"
homepage = "https://blazescript.blazify.rocks/#/"

[dependencies]
mimalloc = { version = "0.1.17", default-features = false }
serde = { version = "1.0", features = ["derive"], default_features = false }
bincode = "1.3.3"

[lib]
path = "src/lib.rs"

[[bin]]
name = "blazescript"
path = "src/main.rs"
test = false

[profile.release]
debug = 0
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.release.package."*"]
debug = 0
opt-level = 3
codegen-units = 1
