[package]
name = "blazescript"
version = "0.0.1"
authors = ["RoMeAh <romeah@blazify.rocks>"]
edition = "2018"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/BlazifyOrg/blazescript"
homepage = "https://blazescript.blazify.rocks/"
build = "build.rs"

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "blazescript"
path = "src/main.rs"
test = false