[package]
name = "blazescript"
version = "1.0.0-SNAPSHOT"
authors = ["RoMeAh <teamblazeyt3129@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/BlazifyOrg/blazescript"
homepage = "https://blazify.rocks/"

[dependencies]
rustyline = "8.0.0"
structopt = "0.3.13"

[lib]
path = "src/lib.rs"

[[bin]]
name = "blazescript"
path = "src/main.rs"
test = false