[package]
name = "blazescript"
version = "1.0.0-SNAPSHOT"
authors = ["RoMeAh <romeah@blazify.rocks>"]
edition = "2018"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/BlazifyOrg/blazescript"
homepage = "https://blazify.rocks/"

[dependencies]

[lib]
path = "src/lib.rs"

[[bin]]
name = "blazescript"
path = "src/main.rs"
test = false