#!/bin/sh
set -e

bzs_install="${BZS_INSTALL:-$HOME/.bzs}"
bin_dir="$bzs_install/bin"

if [ ! -d "$bin_dir" ]; then
	mkdir -p "$bin_dir"
fi

cd $bin_dir

if [ "$OS" = "Windows_NT" ]; then
	target="blazex-windows.exe"
    exe="$bin_dir/blazex.exe"
else
	case $(uname -sm) in
	"Darwin x86_64") target="blazex-apple" ;;
	*) target="blazex-linux" ;;
	esac
    exe="$bin_dir/blazex"
fi


if [ $# -eq 0 ]; then
	bzs_uri="https://github.com/BlazifyOrg/blazex/releases/latest/download/${target}"
else
	bzs_uri="https://github.com/BlazifyOrg/blazex/releases/download/${1}/${target}"
fi

curl --fail --location --progress-bar --output "$exe" "$bzs_uri"
chmod u+x "$exe"

if command -v blazex >/dev/null; then
    echo "Run 'blazex path/to/file.bzx' to get started"
else
    case $SHELL in
    	/bin/zsh) shell_profile=".zshrc" ;;
    	*) shell_profile=".bash_profile" ;;
    esac

    echo "Manually add the directory to your \$HOME/$shell_profile (or similar)"
    echo "  export BZS_INSTALL=\"$bzs_install\""
    echo "  export PATH=\"\$BZS_INSTALL/bin:\$PATH\""
    echo "Run '$exe path/to/file.bzx' to get started"
fi
