[package]
name = "bzxc_type_system"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bzxc_shared = { path = "../bzxc_shared" }
llvm-sys = "100.0"