name: Build and upload binaries to release

on:
  repository_dispatch:
    types: [tag-created]

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: x86_64-unknown-linux-gnu
          # TODO: uncomment the below when github allows 11.0
          # - os: macos-11.0
          #  artifact_name: aarch64-apple-darwin
          - os: macos-10.15
            artifact_name: x86_64-apple-darwin
          - os: windows-latest
            artifact_name: x86_64-pc-windows-msvc.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
      - name: Build project
        run: bash build ${{ runner.temp }}/llvm
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.artifact_name }}
          tag: ${{ github.event.client_payload.new_version }}

  bench:
    name: Benchmarmks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Benches Graph
        run: |
          rustup toolchain install nightly
          rustup override set nightly
          rustup component add rust-src
          cargo +nightly bench
          mkdir -p ${{ github.event.client_payload.new_version }}
          cp -r target/criterion/ ${{ github.event.client_payload.new_version }}
      - name: Checkout the benches branch
        run: |
          git fetch
          git checkout benches -f
      - name: Configure git identity
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Stage, commit & push changes
        run: |
          git add ${{ github.event.client_payload.new_version }}
          git commit -m  "Benches update triggered by ${{ github.event.client_payload.new_version }}"
          git push origin benches
