name: Build and upload binaries to release

on:
  repository_dispatch:
    types: [tag-created]

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: blazescript
            asset_name: blazescript-linux
          - os: macos-latest
            artifact_name: blazescript
            asset_name: blazescript-macos
          - os: windows-latest
            artifact_name: blazescript.exe
            asset_name: blazescript-windows.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: ./build.sh
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.event.client_payload.new_version }}
