name: Build and upload binaries to release

on:
  repository_dispatch:
    types: [tag-created]

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: blazex-linux
            binary: blazex
          - os: macos-10.15
            artifact_name: blazex-apple
            binary: blazex
          # - os: windows-latest
          #   artifact_name: blazex-windows.exe
          #   binary: blazex.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
      - name: Build project
        run: bash build ${{ runner.temp }}/llvm
        env:
          LLVM_SYS_110_PREFIX: ${{ runner.temp }}/llvm
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/${{ matrix.binary }}
          asset_name: ${{ matrix.artifact_name }}
          tag: ${{ github.event.client_payload.new_version }}
