name: Build and upload binaries to release

on:
  repository_dispatch:
    types: [tag-created]

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: x86_64-unknown-linux-gnu
          - os: macos-latest
            artifact_name: aarch64-apple-darwin
          - os: macos-10.15
            artifact_name: x86_64-apple-darwin
          - os: windows-latest
            artifact_name: x86_64-pc-windows-msvc.exee
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: bash ./build.sh
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.event.client_payload.new_version }}
