name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: blazex-linux
            exe: main
          - os: macos-10.15
            artifact_name: blazex-apple
            exe: main
          - os: windows-latest
            artifact_name: blazex-windows.exe
            exe: main.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
      - name: Build project
        run: bash build ${{ runner.temp }}/llvm
        env:
          LLVM_SYS_110_PREFIX: ${{ runner.temp }}/llvm
      - name: Compile to Object Code
        run: ./bin/${{ matrix.artifact_name }} examples/main.bzx
      - name: Link to libc and compile to native machine executable
        run: clang -o${{ matrix.exe }} -Ofast -lc examples/main.o
      - name: Run Native Executable
        run: ./${{ matrix.exe }}
