name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: blazescript
          - os: macos-latest
            artifact_name: blazescript
          - os: windows-latest
            artifact_name: blazescript.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: bash ./build.sh
      - name: Compile
        run: ./bin/${{ matrix.artifact_name }} examples/main.bzs
      - name: Interpret
        run: ./bin/${{ matrix.artifact_name }} examples/main.bze
