name: Blazescript

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cargo run --release --quiet -- examples/main.bzs
          echo \n\n
          cargo run --release --quiet -- examples/main.bze
