name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: blazescript
          - os: macos-latest
            artifact_name: blazescript
          - os: windows-latest
            artifact_name: blazescript.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: cargo build --release
      - name: Strip Executable
        run: strip target/release/${{ matrix.artifact_name }}
      - name: Compile
        run: ./target/release/${{ matrix.artifact_name }} examples/main.bzs
      - name: Interpret
        run: ./target/release/${{ matrix.artifact_name }} examples/main.bze
