name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: blazex
            exe: main
          - os: macos-10.15
            artifact_name: blazex
            exe: main
          - os: windows-latest
            artifact_name: blazex.exe
            exe: main.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with: ~/.cache
      - uses: lukka/get-cmake@latest
      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10
      - name: Run CMake consuming CMakePreset.json and vcpkg.json by mean of vcpkg.
        uses: lukka/run-cmake@v10
      - name: Build project
        run: make build
      - name: Compile to Object Code
        run: ./bin/${{ matrix.artifact_name }} examples/main.bzx
      - name: Link to libc and compile to native machine executable
        run: clang -o${{ matrix.exe }} -Ofast -lc examples/main.o
      - name: Run Native Executable
        run: ./${{ matrix.exe }}
