name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: x86_64-unknown-linux-gnu
          # TODO: uncomment the below when github allows 11.0
          # - os: macos-11.0
          #  artifact_name: aarch64-apple-darwin
          - os: macos-10.15
            artifact_name: x86_64-apple-darwin
          - os: windows-latest
            artifact_name: x86_64-pc-windows-msvc.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0.1"
          directory: ${{ runner.temp }}/llvm
      - name: Build project
        run: LLVM_SYS_110_PREFIX=${{ runner.temp }}/llvm bash build
      - name: Compile
        run: ./bin/${{ matrix.artifact_name }} examples/main.bzs
      - name: Interpret
        run: ./bin/${{ matrix.artifact_name }} examples/main.bze